version: "3.8"
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.4
    ports:
    - 8080:8080
    - 50051:50051
    container_name: weaviate
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - diagno_sys_network

  rag_server:
    build:
      context: .
      dockerfile: Dockerfile.rag
    volumes:
      - model_data:/app/embedding_models
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL=http://weaviate:8080 
      - MODEL_NAME=BAAI/bge-m3
    ports:
      - "8001:8001"
    container_name: rag_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - diagno_sys_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - diagno_sys_network

  diagno_sys:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - OLLAMA_URL=http://ollama:11434
    container_name: diagno_sys
    ports:
      - "8501:8501"
    depends_on:
      - weaviate
      - ollama
    networks:
      - diagno_sys_network

volumes:
  model_data:
    driver: local
  weaviate_data:
    driver: local

networks:
  diagno_sys_network:
    driver: bridge
