version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__STORAGE__PATH: "/qdrant/storage"

  rag_server:
    build:
      context: .
      dockerfile: Dockerfile.rag
    volumes:
      - model_data:/app/embedding_models
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333 
      - MODEL_NAME=BAAI/bge-m3
    ports:
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  diagno_sys:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - OLLAMA_URL=http://ollama:11434
    container_name: diagno_sys
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
      - ollama

volumes:
  model_data:
    driver: local
  qdrant_data:
    driver: local
