version: "3.8"
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.4
    ports:
      - 8080:8080
      - 50051:50051
    container_name: weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
    networks:
      - diagno_sys_network

  rag_server:
    build:
      context: .
      dockerfile: Dockerfile.rag
    volumes:
      - model_data:/app/embedding_models
      - model_data:/app/reranker_models
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL=http://weaviate:8080
      - EMBEDDING_MODEL_NAME=onurwest361/diagnosys_bge_m3
      - RERANKER_MODEL_NAME=BAAI/bge-reranker-v2-m3
      - COLLECTION_NAME=med_documents
    ports:
      - "8001:8001"
    container_name: rag_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    networks:
      - diagno_sys_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    networks:
      - diagno_sys_network
    volumes:
      - ./data/ollama:/root/.ollama

  diagno_sys:
    build:
      context: .
      dockerfile: Dockerfile.app
      #https://b9zbcrb3kof786-11434.proxy.runpod.net/ oozcan361/diagnosys_v0.1:70b
    environment:
      - OLLAMA_URL=https://b9zbcrb3kof786-11434.proxy.runpod.net/
      - TEMPERATURE=0.4
      - CHAT_MODEL_NAME=oozcan361/diagnosys_v0.1:70b
      - NAMER_MODEL_NAME=llama3.1
      - ANALYZER_MODEL_NAME=oozcan361/diagnosys_v0.1:70b
    container_name: diagno_sys
    ports:
      - "8501:8501"
    depends_on:
      - rag_server
      - ollama
    networks:
      - diagno_sys_network

volumes:
  model_data:
    driver: local
  weaviate_data:
    driver: local
  ollama:
    driver: local

networks:
  diagno_sys_network:
    driver: bridge
